 int(), long(), float(), complex()
  str(), unicode(), basestring()
  list(), tuple()
  type()
  dict()  bool()
 set(), frozenset()  object()  classmethod()
  staticmethod()   super()
  property()
  file()